In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from scipy import stats

%matplotlib inline

In [2]:
df_test = pd.DataFrame({
    "A":[1,2,3,4,5]
})
df_test

A
0  1
1  2
2  3
3  4
4  5

In [3]:
list_size_odd = [1,2,3,4,5]
list_size_even = [1,2,3,4,5]

In [4]:
np.random.seed(0);
# np random integers between [a,b] with size=n
np.random.randint(1,10,10) 
x_even = list(np.random.randint(1,10,11))
x_odd = x_even[0:len(x_even)-1]

In [5]:
x_even

[7, 9, 9, 2, 7, 8, 8, 9, 2, 6, 9]

In [43]:
x_odd

[2, 2, 6, 7, 7, 8, 8, 9, 9, 9]

In [57]:
len(x_odd)-1
int((9+1)/2)
x_odd[5]

8

In [82]:
n = len(x_odd)
1/2*(x_odd[int(n/2)] + x_odd[int(n/(2+1))])

7.5

In [53]:
np.median(x_even)

8.0

In [54]:
np.median(x_odd)

7.5

In [86]:
def median(data):
    data.sort()
    size_n = len(data)
    if ((size_n % 2) == 0):
        n = size_n
        median = 1/2*(data[int(n/2)] + data[int(n/(2+1))])
    else:
        median = data[int((size_n+1)/2)]
    return median

In [87]:
median(x_even)

8

In [90]:
len(x_odd)

10

In [92]:
median(x_odd)

7.5

In [29]:
np_x_even = np.array(x_even)
np_x_even

array([2, 2, 6, 7, 7, 8, 8, 9, 9, 9, 9])

In [24]:
pd_x_even = pd.Series(np_x_even)

In [25]:
pd_x_even.median()

8.0

In [15]:
np_x_odd = np.array(x_odd)
np_x_odd

array([2, 2, 6, 7, 7, 8, 8, 9, 9, 9])

In [16]:
pd_x_odd = pd.Series(np_x_odd)
pd_x_odd.median()

7.5

In [18]:
stats.mode(np_x_odd)

ModeResult(mode=array([9]), count=array([3]))

In [19]:
mode = stats.mode(np_x_odd)
mode[0]

array([9])